// This file was generated by iSukces.Templates ver 1.24.728.1

using iSukces.Base;
using System.Globalization;

namespace iSukces.Templates.Demo;

public readonly record struct PrimaryKey(int Value): IComparable<int>, IComparable<PrimaryKey>, IEquatable<int>, IPrimitiveWrapper<int>
{
    public bool Equals(int other) => Value.Equals(other);

    public int CompareTo(PrimaryKey other) => Value.CompareTo(other.Value);

    public int CompareTo(int other) => Value.CompareTo(other);

    public static PrimaryKey Parse(string? text)
    {
        text = text?.Trim();
        if (string.IsNullOrEmpty(text))
            throw new ArgumentException("", nameof(text));
        return new PrimaryKey(int.Parse(text, CultureInfo.InvariantCulture));
    }

    public static PrimaryKey? FromNullable(int? value)
        => value is null ? null : new PrimaryKey(value.Value);

}

