// This file was generated by iSukces.Templates ver 1.25.1021.7
// Get latest version from https://raw.githubusercontent.com/isukces/iSukces.Templates/main/Code/iSukces.Templates/MvvmBuilder.ttinclude

// hello
using System.ComponentModel;
using System.Runtime.CompilerServices;

namespace iSukces.Templates.Demo;

public class MvvmDemo<TItem>
{
    protected void OnPropertyChanged([CallerMemberName] string? propertyName = null)
    {
        PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
    }

    protected bool SetAndNotify<T>(ref T field, T value, [CallerMemberName] string? propertyName = null)
    {
        if (EqualityComparer<T>.Default.Equals(field, value)) return false;
        field = value;
        OnPropertyChanged(propertyName);
        System.Console.WriteLine();
        return true;
    }

    public string Name1
    {
        get => _name1;
        set => SetAndNotify(ref _name1, value);
    }

    private string _name1;

    public event PropertyChangedEventHandler? PropertyChanged;

}
