using System.Diagnostics;
using System.Reflection;

namespace iSukces.Templates.Builder;

internal class Program
{
    private static string GetAssembyVersion()
    {
        var assembly = Assembly.GetExecutingAssembly();
        var fvi      = FileVersionInfo.GetVersionInfo(assembly.Location);
        return fvi.FileVersion;
    }

    private static void Main(string[] args)
    {
        Console.WriteLine("Preparing PrimitiveObsession.ttinclude");
        var welcome = "This file was generated by iSukces.Templates ver " + GetAssembyVersion();
        var header = new[]
        {
            welcome,
            "Get the latest version from https://raw.githubusercontent.com/isukces/iSukces.Templates/main/Code/iSukces.Templates/PrimitiveObsession.ttinclude"
        };
        new CsMerge(header)
            .WithProject("iSukces.Templates.Builder.csproj")
            .WithSource("PrimitiveObsessionClasses\\Config.cs", Fla.IgnoreAllEmptyLines)
            .WithSource("PrimitiveObsessionClasses\\Features.cs", Fla.IgnoreAllEmptyLines)
            .WithSource("PrimitiveObsessionClasses\\TypeConversion.cs", Fla.IgnoreAllEmptyLines)
            .WithSource("Common\\CaseExpressionItem.cs", Fla.IgnoreAllEmptyLines)
            .WithSource("Common\\CodeWriterBase.cs")
            .WithSource("PrimitiveObsessionClasses\\PrimitiveObsessionBase.cs")
            .WithSource("PrimitiveObsessionClasses\\IntKey.cs")
            .WithSource("PrimitiveObsessionClasses\\StringKey.cs")
            .WithSource("PrimitiveObsessionClasses\\GuidKey.cs")
            .WithSource("PrimitiveObsessionClasses\\DoubleKey.cs")
            .WithProject("iSukces.Templates.sln")
            .WriteTo("iSukces.Templates\\PrimitiveObsession.ttinclude")
            ;
        
        header =
        [
            welcome,
            "Get the latest version from https://raw.githubusercontent.com/isukces/iSukces.Templates/main/Code/iSukces.Templates/MvvmBuilder.ttinclude"
        ];
        new CsMerge(header)
            .WithProject("iSukces.Templates.Builder.csproj")
            .WithSource("MvvmClasses\\Features.cs", Fla.IgnoreAllEmptyLines)
            .WithSource("MvvmClasses\\Property.cs", Fla.IgnoreAllEmptyLines)
            .WithSource("MvvmClasses\\MvvmBuilder.cs", Fla.IgnoreAllEmptyLines)
            /*
            .WithSource("PrimitiveObsessionClasses\\TypeConversion.cs", Fla.IgnoreAllEmptyLines)
            .WithSource("Common\\CaseExpressionItem.cs", Fla.IgnoreAllEmptyLines)
            */
            .WithSource("Common\\CaseExpressionItem.cs", Fla.IgnoreAllEmptyLines)
            .WithSource("Common\\CodeWriterBase.cs")
            /*
            .WithSource("PrimitiveObsessionClasses\\PrimitiveObsessionBase.cs")
            .WithSource("PrimitiveObsessionClasses\\IntKey.cs")
            .WithSource("PrimitiveObsessionClasses\\StringKey.cs")
            .WithSource("PrimitiveObsessionClasses\\GuidKey.cs")
            .WithSource("PrimitiveObsessionClasses\\DoubleKey.cs")
            */
            .WithProject("iSukces.Templates.sln")
            .WriteTo("iSukces.Templates\\MvvmBuilder.ttinclude")
            ;
        
        Console.WriteLine("Done");
    }
}